(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// object to store loaded and loading wasm modules
/******/ 	var installedWasmModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// object with all compiled WebAssembly.Modules
/******/ 	__webpack_require__.w = {};
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var styles_AppComponent = [];
var RenderType_AppComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 16777216, null, null, 1, "router-outlet", [], null, null, null, null, null)), i0.ɵdid(1, 212992, null, 0, i1.RouterOutlet, [i1.ChildrenOutletContexts, i0.ViewContainerRef, i0.ComponentFactoryResolver, [8, null], i0.ChangeDetectorRef], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i0.ɵdid(1, 49152, null, 0, i2.AppComponent, [], null, null)], null, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i0.ɵccf("app-root", i2.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppComponent = /** @class */ (function () {
    function AppComponent() {
    }
    return AppComponent;
}());
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppModule = /** @class */ (function () {
    function AppModule() {
    }
    return AppModule;
}());
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
var i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var i3 = __webpack_require__(/*! ./home/home.component.ngfactory */ "./src/app/home/home.component.ngfactory.js");
var i4 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
var i5 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i6 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
var i7 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
var i8 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
var i9 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
var i10 = __webpack_require__(/*! @angular/flex-layout/core */ "@angular/flex-layout/core");
var i11 = __webpack_require__(/*! @angular/router */ "@angular/router");
var i12 = __webpack_require__(/*! @nguniversal/common */ "@nguniversal/common");
var i13 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var i14 = __webpack_require__(/*! @angular/service-worker */ "@angular/service-worker");
var i15 = __webpack_require__(/*! @angular/http */ "@angular/http");
var i16 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
var i17 = __webpack_require__(/*! @angular/flex-layout/server */ "@angular/flex-layout/server");
var i18 = __webpack_require__(/*! @nguniversal/module-map-ngfactory-loader */ "@nguniversal/module-map-ngfactory-loader");
var i19 = __webpack_require__(/*! ./home/home.component */ "./src/app/home/home.component.ts");
var i20 = __webpack_require__(/*! @angular/cdk/bidi */ "@angular/cdk/bidi");
var i21 = __webpack_require__(/*! @angular/flex-layout/flex */ "@angular/flex-layout/flex");
var i22 = __webpack_require__(/*! @angular/flex-layout/extended */ "@angular/flex-layout/extended");
var i23 = __webpack_require__(/*! @angular/flex-layout */ "@angular/flex-layout");
var i24 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.HomeComponentNgFactory, i4.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_l, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i5.NgLocalization, i5.NgLocaleLocalization, [i0.LOCALE_ID, [2, i5.ɵangular_packages_common_common_a]]), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_j, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_k, []), i0.ɵmpd(4608, i6.DomSanitizer, i6.ɵangular_packages_platform_browser_platform_browser_e, [i5.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i6.DomSanitizer]), i0.ɵmpd(4608, i6.HAMMER_GESTURE_CONFIG, i6.HammerGestureConfig, []), i0.ɵmpd(5120, i6.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p1_0, p2_0, p2_1, p2_2) { return [new i6.ɵDomEventsPlugin(p0_0, p0_1), new i6.ɵKeyEventsPlugin(p1_0), new i6.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2)]; }, [i5.DOCUMENT, i0.NgZone, i5.DOCUMENT, i5.DOCUMENT, i6.HAMMER_GESTURE_CONFIG, i0.ɵConsole]), i0.ɵmpd(4608, i6.EventManager, i6.EventManager, [i6.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i6.ɵDomSharedStylesHost, i6.ɵDomSharedStylesHost, [i5.DOCUMENT]), i0.ɵmpd(4608, i6.ɵDomRendererFactory2, i6.ɵDomRendererFactory2, [i6.EventManager, i6.ɵDomSharedStylesHost]), i0.ɵmpd(4608, i7.ɵangular_packages_platform_server_platform_server_c, i7.ɵangular_packages_platform_server_platform_server_c, [i6.DOCUMENT, [2, i6.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i6.ɵSharedStylesHost, null, [i7.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i7.ɵServerRendererFactory2, i7.ɵServerRendererFactory2, [i0.NgZone, i6.DOCUMENT, i6.ɵSharedStylesHost]), i0.ɵmpd(4608, i8.AnimationDriver, i8.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i8.ɵAnimationStyleNormalizer, i9.ɵangular_packages_platform_browser_animations_animations_c, []), i0.ɵmpd(4608, i8.ɵAnimationEngine, i9.ɵangular_packages_platform_browser_animations_animations_a, [i8.AnimationDriver, i8.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i7.ɵangular_packages_platform_server_platform_server_a, [i7.ɵServerRendererFactory2, i8.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(4608, i6.Meta, i6.Meta, [i5.DOCUMENT]), i0.ɵmpd(4608, i6.Title, i6.Title, [i5.DOCUMENT]), i0.ɵmpd(4608, i10.MatchMedia, i10.ServerMatchMedia, [i0.NgZone, i0.PLATFORM_ID, i5.DOCUMENT]), i0.ɵmpd(4608, i10.ObservableMedia, i10.MediaService, [i10.BreakPointRegistry, i10.MatchMedia]), i0.ɵmpd(5120, i11.ROUTER_INITIALIZER, i11.ɵangular_packages_router_router_i, [i11.ɵangular_packages_router_router_g]), i0.ɵmpd(5120, i0.APP_BOOTSTRAP_LISTENER, function (p0_0, p0_1, p1_0) { return [i10.removeStyles(p0_0, p0_1), p1_0]; }, [i5.DOCUMENT, i0.PLATFORM_ID, i11.ROUTER_INITIALIZER]), i0.ɵmpd(4608, i6.TransferState, i6.TransferState, []), i0.ɵmpd(4608, i12.ɵnguniversal_modules_common_common_a, i12.ɵnguniversal_modules_common_common_a, [i0.ApplicationRef, i6.TransferState]), i0.ɵmpd(4608, i13.HttpXsrfTokenExtractor, i13.ɵangular_packages_common_http_http_h, [i5.DOCUMENT, i0.PLATFORM_ID, i13.ɵangular_packages_common_http_http_f]), i0.ɵmpd(4608, i13.ɵangular_packages_common_http_http_i, i13.ɵangular_packages_common_http_http_i, [i13.HttpXsrfTokenExtractor, i13.ɵangular_packages_common_http_http_g]), i0.ɵmpd(5120, i13.HTTP_INTERCEPTORS, function (p0_0, p1_0) { return [p0_0, p1_0]; }, [i12.ɵnguniversal_modules_common_common_a, i13.ɵangular_packages_common_http_http_i]), i0.ɵmpd(5120, i14.ɵangular_packages_service_worker_service_worker_e, i14.ɵangular_packages_service_worker_service_worker_d, [i14.ɵangular_packages_service_worker_service_worker_a, i0.PLATFORM_ID]), i0.ɵmpd(4608, i14.SwPush, i14.SwPush, [i14.ɵangular_packages_service_worker_service_worker_e]), i0.ɵmpd(4608, i14.SwUpdate, i14.SwUpdate, [i14.ɵangular_packages_service_worker_service_worker_e]), i0.ɵmpd(5120, i11.ActivatedRoute, i11.ɵangular_packages_router_router_f, [i11.Router]), i0.ɵmpd(4608, i11.NoPreloading, i11.NoPreloading, []), i0.ɵmpd(6144, i11.PreloadingStrategy, null, [i11.NoPreloading]), i0.ɵmpd(135680, i11.RouterPreloader, i11.RouterPreloader, [i11.Router, i0.NgModuleFactoryLoader, i0.Compiler, i0.Injector, i11.PreloadingStrategy]), i0.ɵmpd(4608, i11.PreloadAllModules, i11.PreloadAllModules, []), i0.ɵmpd(4608, i15.BrowserXhr, i7.ɵangular_packages_platform_server_platform_server_d, []), i0.ɵmpd(4608, i15.ResponseOptions, i15.BaseResponseOptions, []), i0.ɵmpd(4608, i15.XSRFStrategy, i7.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i15.XHRBackend, i15.XHRBackend, [i15.BrowserXhr, i15.ResponseOptions, i15.XSRFStrategy]), i0.ɵmpd(4608, i15.RequestOptions, i15.BaseRequestOptions, []), i0.ɵmpd(5120, i15.Http, i7.ɵangular_packages_platform_server_platform_server_f, [i15.XHRBackend, i15.RequestOptions]), i0.ɵmpd(4608, i13.XhrFactory, i7.ɵangular_packages_platform_server_platform_server_d, []), i0.ɵmpd(4608, i13.HttpXhrBackend, i13.HttpXhrBackend, [i13.XhrFactory]), i0.ɵmpd(6144, i13.HttpBackend, null, [i13.HttpXhrBackend]), i0.ɵmpd(5120, i13.HttpHandler, i7.ɵangular_packages_platform_server_platform_server_g, [i13.HttpBackend, [2, i13.HTTP_INTERCEPTORS]]), i0.ɵmpd(4608, i13.HttpClient, i13.HttpClient, [i13.HttpHandler]), i0.ɵmpd(4608, i13.ɵangular_packages_common_http_http_e, i13.ɵangular_packages_common_http_http_e, []), i0.ɵmpd(4608, i16.AnimationBuilder, i9.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i6.DOCUMENT]), i0.ɵmpd(5120, i7.BEFORE_APP_SERIALIZED, function (p0_0, p0_1, p0_2, p0_3, p1_0, p1_1, p1_2) { return [i17.FLEX_SSR_SERIALIZER_FACTORY(p0_0, p0_1, p0_2, p0_3), i7.ɵangular_packages_platform_server_platform_server_b(p1_0, p1_1, p1_2)]; }, [i10.StylesheetMap, i10.MatchMedia, i5.DOCUMENT, i10.BREAKPOINTS, i6.DOCUMENT, i0.APP_ID, i6.TransferState]), i0.ɵmpd(1073742336, i5.CommonModule, i5.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i6.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(1024, i0.NgProbeToken, function () { return [i11.ɵangular_packages_router_router_b()]; }, []), i0.ɵmpd(256, i0.APP_ID, "my-app", []), i0.ɵmpd(2048, i6.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(512, i11.ɵangular_packages_router_router_g, i11.ɵangular_packages_router_router_g, [i0.Injector]), i0.ɵmpd(256, i14.ɵangular_packages_service_worker_service_worker_b, "/ngsw-worker.js", []), i0.ɵmpd(256, i14.ɵangular_packages_service_worker_service_worker_a, { enabled: true }, []), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p1_1, p1_2, p2_0, p3_0, p3_1, p3_2, p3_3) { return [i6.ɵangular_packages_platform_browser_platform_browser_h(p0_0), i6.ɵangular_packages_platform_browser_platform_browser_f(p1_0, p1_1, p1_2), i11.ɵangular_packages_router_router_h(p2_0), i14.ɵangular_packages_service_worker_service_worker_c(p3_0, p3_1, p3_2, p3_3)]; }, [[2, i0.NgProbeToken], i6.ɵTRANSITION_ID, i5.DOCUMENT, i0.Injector, i11.ɵangular_packages_router_router_g, i0.Injector, i14.ɵangular_packages_service_worker_service_worker_b, i14.ɵangular_packages_service_worker_service_worker_a, i0.PLATFORM_ID]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i6.BrowserModule, i6.BrowserModule, [[3, i6.BrowserModule]]), i0.ɵmpd(1024, i11.ɵangular_packages_router_router_a, i11.ɵangular_packages_router_router_d, [[3, i11.Router]]), i0.ɵmpd(512, i11.UrlSerializer, i11.DefaultUrlSerializer, []), i0.ɵmpd(512, i11.ChildrenOutletContexts, i11.ChildrenOutletContexts, []), i0.ɵmpd(256, i11.ROUTER_CONFIGURATION, {}, []), i0.ɵmpd(1024, i5.LocationStrategy, i11.ɵangular_packages_router_router_c, [i5.PlatformLocation, [2, i5.APP_BASE_HREF], i11.ROUTER_CONFIGURATION]), i0.ɵmpd(512, i5.Location, i5.Location, [i5.LocationStrategy]), i0.ɵmpd(512, i0.Compiler, i0.Compiler, []), i0.ɵmpd(512, i0.NgModuleFactoryLoader, i18.ModuleMapNgFactoryLoader, [i0.Compiler, i18.MODULE_MAP]), i0.ɵmpd(1024, i11.ROUTES, function () { return [[{ path: "", component: i19.HomeComponent, pathMatch: "full" }, { path: "lazy", loadChildren: "./lazy/lazy.module#LazyModule" }, { path: "lazy/nested", loadChildren: "./lazy/lazy.module#LazyModule" }]]; }, []), i0.ɵmpd(1024, i11.Router, i11.ɵangular_packages_router_router_e, [i0.ApplicationRef, i11.UrlSerializer, i11.ChildrenOutletContexts, i5.Location, i0.Injector, i0.NgModuleFactoryLoader, i0.Compiler, i11.ROUTES, i11.ROUTER_CONFIGURATION, [2, i11.UrlHandlingStrategy], [2, i11.RouteReuseStrategy]]), i0.ɵmpd(1073742336, i11.RouterModule, i11.RouterModule, [[2, i11.ɵangular_packages_router_router_a], [2, i11.Router]]), i0.ɵmpd(1073742336, i10.CoreModule, i10.CoreModule, []), i0.ɵmpd(1073742336, i20.BidiModule, i20.BidiModule, []), i0.ɵmpd(1073742336, i21.FlexModule, i21.FlexModule, []), i0.ɵmpd(1073742336, i22.ExtendedModule, i22.ExtendedModule, []), i0.ɵmpd(256, i10.SERVER_TOKEN, true, []), i0.ɵmpd(1073742336, i23.FlexLayoutModule, i23.FlexLayoutModule, [[2, i10.SERVER_TOKEN], i0.PLATFORM_ID]), i0.ɵmpd(1073742336, i6.BrowserTransferStateModule, i6.BrowserTransferStateModule, []), i0.ɵmpd(1073742336, i12.TransferHttpCacheModule, i12.TransferHttpCacheModule, []), i0.ɵmpd(1073742336, i14.ServiceWorkerModule, i14.ServiceWorkerModule, []), i0.ɵmpd(1073742336, i24.AppModule, i24.AppModule, []), i0.ɵmpd(1073742336, i15.HttpModule, i15.HttpModule, []), i0.ɵmpd(1073742336, i13.HttpClientXsrfModule, i13.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i13.HttpClientModule, i13.HttpClientModule, []), i0.ɵmpd(1073742336, i9.NoopAnimationsModule, i9.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i7.ServerModule, i7.ServerModule, []), i0.ɵmpd(1073742336, i17.FlexLayoutServerModule, i17.FlexLayoutServerModule, []), i0.ɵmpd(1073742336, i18.ModuleMapLoaderModule, i18.ModuleMapLoaderModule, []), i0.ɵmpd(1073742336, i7.ServerTransferStateModule, i7.ServerTransferStateModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i13.ɵangular_packages_common_http_http_f, "XSRF-TOKEN", []), i0.ɵmpd(256, i13.ɵangular_packages_common_http_http_g, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i9.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppServerModule = /** @class */ (function () {
    function AppServerModule() {
    }
    return AppServerModule;
}());
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/home/home.component.ngfactory.js":
/*!**************************************************!*\
  !*** ./src/app/home/home.component.ngfactory.js ***!
  \**************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./home.css.shim.ngstyle */ "./src/app/home/home.css.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! @angular/flex-layout/flex */ "@angular/flex-layout/flex");
var i3 = __webpack_require__(/*! @angular/flex-layout/core */ "@angular/flex-layout/core");
var i4 = __webpack_require__(/*! ./home.component */ "./src/app/home/home.component.ts");
var styles_HomeComponent = [i0.styles];
var RenderType_HomeComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_HomeComponent, data: {} });
exports.RenderType_HomeComponent = RenderType_HomeComponent;
function View_HomeComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 271, "div", [["class", "container"], ["fxLayout", "row"], ["fxLayoutAlign", "center center"]], null, null, null, null, null)), i1.ɵdid(1, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(2, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [6, i2.LayoutDirective], i3.StyleUtils], { align: [0, "align"] }, null), (_l()(), i1.ɵeld(3, 0, null, null, 268, "div", [["class", "content"], ["fxLayout", "column"], ["fxLayout.gt-sm", "row"]], null, null, null, null, null)), i1.ɵdid(4, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"], layoutGtSm: [1, "layoutGtSm"] }, null), (_l()(), i1.ɵeld(5, 0, null, null, 45, "div", [["class", "container-margin u-flexFix"], ["fxFlex", "0 0 auto"], ["fxFlex.gt-sm", "0 0 220px"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(6, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(7, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"], flexGtSm: [1, "flexGtSm"] }, null), (_l()(), i1.ɵeld(8, 0, null, null, 3, "div", [["class", "img"], ["fxFlex", "0 0 auto"], ["fxLayoutAlign", "start center"]], null, null, null, null, null)), i1.ɵdid(9, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [8, null], i3.StyleUtils], { align: [0, "align"] }, null), i1.ɵdid(10, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(11, 0, null, null, 0, "img", [["src", "../../assets/images/user.png"], ["width", "100%"]], null, null, null, null, null)), (_l()(), i1.ɵeld(12, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(13, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(14, 0, null, null, 9, "div", [["class", "name-text"], ["fxFlex", "0 0 auto"], ["fxLayout", "row wrap"], ["fxLayoutAlign", "start center"]], null, null, null, null, null)), i1.ɵdid(15, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(16, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [6, i2.LayoutDirective], i3.StyleUtils], { align: [0, "align"] }, null), i1.ɵdid(17, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(18, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Justin"])), (_l()(), i1.ɵeld(20, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Ruben"])), (_l()(), i1.ɵeld(22, 0, null, null, 1, "span", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Parra"])), (_l()(), i1.ɵeld(24, 0, null, null, 1, "div", [["fxFlex", "0 0 20px"]], null, null, null, null, null)), i1.ɵdid(25, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(26, 0, null, null, 5, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "row"], ["fxLayoutAlign", "start center"]], null, null, null, null, null)), i1.ɵdid(27, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(28, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [6, i2.LayoutDirective], i3.StyleUtils], { align: [0, "align"] }, null), i1.ɵdid(29, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(30, 0, null, null, 1, "a", [["href", "tel:+15127669027"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["+1 512 766 9027"])), (_l()(), i1.ɵeld(32, 0, null, null, 5, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "row"], ["fxLayoutAlign", "start center"]], null, null, null, null, null)), i1.ɵdid(33, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(34, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [6, i2.LayoutDirective], i3.StyleUtils], { align: [0, "align"] }, null), i1.ɵdid(35, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(36, 0, null, null, 1, "a", [["href", "tel:+19158207620"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["+1 915 820 7620"])), (_l()(), i1.ɵeld(38, 0, null, null, 1, "div", [["fxFlex", "0 0 10px"]], null, null, null, null, null)), i1.ɵdid(39, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(40, 0, null, null, 2, "div", [["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(41, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" El Paso Texas, United States "])), (_l()(), i1.ɵeld(43, 0, null, null, 1, "div", [["fxFlex", "0 0 10px"]], null, null, null, null, null)), i1.ɵdid(44, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(45, 0, null, null, 5, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "row"], ["fxLayoutAlign", "start center"]], null, null, null, null, null)), i1.ɵdid(46, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(47, 737280, null, 0, i2.LayoutAlignDirective, [i3.MediaMonitor, i1.ElementRef, [6, i2.LayoutDirective], i3.StyleUtils], { align: [0, "align"] }, null), i1.ɵdid(48, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(49, 0, null, null, 1, "a", [["href", "mailto:contact@parrajust.in"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["contact@parrajust.in"])), (_l()(), i1.ɵeld(51, 0, null, null, 220, "div", [["class", "container-margin"], ["fxFlex", "0 0 auto"], ["fxFlex.gt-sm", "1 1 100%"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(52, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(53, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"], flexGtSm: [1, "flexGtSm"] }, null), (_l()(), i1.ɵeld(54, 0, null, null, 1, "div", [["fxFlex", "0 0 20px"]], null, null, null, null, null)), i1.ɵdid(55, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(56, 0, null, null, 50, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(57, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(58, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(59, 0, null, null, 2, "div", [["class", "division-title"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(60, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Education "])), (_l()(), i1.ɵeld(62, 0, null, null, 44, "div", [["class", "division-group"], ["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(63, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(64, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(65, 0, null, null, 4, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(66, 0, null, null, 1, "a", [["href", "https://www.utep.edu/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["University of Texas at El Paso"])), (_l()(), i1.ɵeld(68, 0, null, null, 1, "span", [["class", "sub"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" \u2014 fall 2015 to spring 2018"])), (_l()(), i1.ɵeld(70, 0, null, null, 13, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(71, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(72, 0, null, null, 1, "span", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Bachelors of Science"])), (_l()(), i1.ɵted(-1, null, [" in "])), (_l()(), i1.ɵeld(75, 0, null, null, 1, "a", [["href", "http://www.cs.utep.edu/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Computer Science"])), (_l()(), i1.ɵted(-1, null, [" with a "])), (_l()(), i1.ɵeld(78, 0, null, null, 1, "span", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["minor"])), (_l()(), i1.ɵted(-1, null, [" in "])), (_l()(), i1.ɵeld(81, 0, null, null, 1, "a", [["href", "https://www.utep.edu/science/math/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Mathematics"])), (_l()(), i1.ɵted(-1, null, [". "])), (_l()(), i1.ɵeld(84, 0, null, null, 5, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(85, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Graduated with a Major "])), (_l()(), i1.ɵeld(87, 0, null, null, 1, "span", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["GPA 3.8 / 4.0"])), (_l()(), i1.ɵted(-1, null, [", Magna Cum Laude. "])), (_l()(), i1.ɵeld(90, 0, null, null, 16, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(91, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Membership in groups: "])), (_l()(), i1.ɵeld(93, 0, null, null, 1, "a", [["href", "https://www.ieee.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["IEEE"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(96, 0, null, null, 1, "a", [["href", "http://mymaes.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["MAES"])), (_l()(), i1.ɵted(-1, null, [" / "])), (_l()(), i1.ɵeld(99, 0, null, null, 1, "a", [["href", "http://www.shpe.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["SHPE"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(102, 0, null, null, 1, "a", [["href", "http://orderofomega.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Order of Omega"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(105, 0, null, null, 1, "a", [["href", "https://www.thetachi.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\u0398\u03A7"])), (_l()(), i1.ɵeld(107, 0, null, null, 1, "div", [["fxFlex", "0 0 20px"]], null, null, null, null, null)), i1.ɵdid(108, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(109, 0, null, null, 127, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(110, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(111, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(112, 0, null, null, 2, "div", [["class", "division-title"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(113, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Experiance "])), (_l()(), i1.ɵeld(115, 0, null, null, 58, "div", [["class", "division-group"], ["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(116, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(117, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(118, 0, null, null, 5, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(119, 0, null, null, 1, "a", [["href", "https://www.utep.edu/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["University of Texas at El Paso"])), (_l()(), i1.ɵted(-1, null, [" Undergrad Research Assistant"])), (_l()(), i1.ɵeld(122, 0, null, null, 1, "span", [["class", "sub"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" \u2014 summer 2016 to spring 2018"])), (_l()(), i1.ɵeld(124, 0, null, null, 2, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(125, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" - Worked closely with professors from the department of computer science on a project whose goal is to improve upon current methods of predicting volcanic behavior, using Recurrent Neural Networks. "])), (_l()(), i1.ɵeld(127, 0, null, null, 2, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(128, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" - Created a three-dimensional viewer for seismic events relating to volcanic eruptions. The tool helped the team visualize events leading up to a volcanic eruption. The tool was created using the open source Electron framework. "])), (_l()(), i1.ɵeld(130, 0, null, null, 1, "div", [["fxFlex", "0 0 10px"]], null, null, null, null, null)), i1.ɵdid(131, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(132, 0, null, null, 3, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(133, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(134, 0, null, null, 1, "div", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["publications:"])), (_l()(), i1.ɵeld(136, 0, null, null, 18, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"], ["fxLayout", "row"]], null, null, null, null, null)), i1.ɵdid(137, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(138, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(139, 0, null, null, 1, "div", [["fxFlex", "0 0 15px"]], null, null, null, null, null)), i1.ɵdid(140, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(141, 0, null, null, 13, "div", [["class", "publication"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["- Parra, Justin; "])), (_l()(), i1.ɵeld(143, 0, null, null, 1, "a", [["href", "http://www.cs.utep.edu/ofuentes/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Fuentes, Olac"])), (_l()(), i1.ɵted(-1, null, ["; "])), (_l()(), i1.ɵeld(146, 0, null, null, 1, "a", [["href", "https://academics.utep.edu/Default.aspx?tabid=70104&ID=eanthony"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Anthony, Elizabeth Y."])), (_l()(), i1.ɵted(-1, null, ["; and "])), (_l()(), i1.ɵeld(149, 0, null, null, 1, "a", [["href", "http://www.cs.utep.edu/vladik/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Kreinovich, Vladik"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(152, 0, null, null, 1, "a", [["href", "https://digitalcommons.utep.edu/cgi/viewcontent.cgi?referer=https://www.google.com/&httpsredir=1&article=2130&context=cs_techrep"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\"Prediction of Volcanic Eruptions as a Case Study of Predicting Rare Events in Chaotic Systems with Delay\""])), (_l()(), i1.ɵted(-1, null, [" (2017). Departmental Technical Reports (CS). 1132."])), (_l()(), i1.ɵeld(155, 0, null, null, 18, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"], ["fxLayout", "row"]], null, null, null, null, null)), i1.ɵdid(156, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(157, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(158, 0, null, null, 1, "div", [["fxFlex", "0 0 15px"]], null, null, null, null, null)), i1.ɵdid(159, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(160, 0, null, null, 13, "div", [["class", "publication"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["- Parra, Justin; "])), (_l()(), i1.ɵeld(162, 0, null, null, 1, "a", [["href", "http://www.cs.utep.edu/ofuentes/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Fuentes, Olac"])), (_l()(), i1.ɵted(-1, null, ["; "])), (_l()(), i1.ɵeld(165, 0, null, null, 1, "a", [["href", "https://academics.utep.edu/Default.aspx?tabid=70104&ID=eanthony"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Anthony, Elizabeth Y."])), (_l()(), i1.ɵted(-1, null, ["; and "])), (_l()(), i1.ɵeld(168, 0, null, null, 1, "a", [["href", "http://www.cs.utep.edu/vladik/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Kreinovich, Vladik"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(171, 0, null, null, 1, "a", [["href", "https://digitalcommons.utep.edu/cgi/viewcontent.cgi?article=2070&context=cs_techrep"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\"Use of Machine Learning to Analyze and -- Hopefully -- Predict Volcano Activity\""])), (_l()(), i1.ɵted(-1, null, [" (2016). Departmental Technical Reports (CS). Paper 1053"])), (_l()(), i1.ɵeld(174, 0, null, null, 62, "div", [["class", "division-group"], ["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(175, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(176, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(177, 0, null, null, 5, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(178, 0, null, null, 1, "a", [["href", "https://www.att.com/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["AT&T"])), (_l()(), i1.ɵted(-1, null, [" Student co-op Technical I"])), (_l()(), i1.ɵeld(181, 0, null, null, 1, "span", [["class", "sub"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" \u2014 spring 2017 to spring 2018"])), (_l()(), i1.ɵeld(183, 0, null, null, 5, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(184, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Worked in the AT&T co-op center in a continuous learning environment while attending "])), (_l()(), i1.ɵeld(186, 0, null, null, 1, "a", [["href", "https://www.utep.edu/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["UTEP"])), (_l()(), i1.ɵted(-1, null, [" full time. "])), (_l()(), i1.ɵeld(189, 0, null, null, 2, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(190, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Create a variety of web applications to solve the needs of several internal AT&T divisions. "])), (_l()(), i1.ɵeld(192, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(193, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(194, 0, null, null, 3, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(195, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(196, 0, null, null, 1, "div", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Wireline-RF Microwave Site"])), (_l()(), i1.ɵeld(198, 0, null, null, 17, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(199, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Orchestrated the total conversions of a Microsoft CSV website into a modern, reactive website. Lead a team of coops through the software development process of the site that provides the means for creating, removing, and updating the pertinent data relating to the operations of microwave sites across the United States by AT&T. Provided a restful application programming interface that provides for expandability through the use of bots. The solution was created with the following technologies: "])), (_l()(), i1.ɵeld(201, 0, null, null, 1, "a", [["href", "https://angular.io/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Angular 5"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(204, 0, null, null, 1, "a", [["href", "https://expressjs.com/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Express"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(207, 0, null, null, 1, "a", [["href", "https://code.visualstudio.com/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Vs code"])), (_l()(), i1.ɵted(-1, null, [", "])), (_l()(), i1.ɵeld(210, 0, null, null, 1, "a", [["href", "https://nodejs.org/en/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["NodeJS"])), (_l()(), i1.ɵted(-1, null, [", and "])), (_l()(), i1.ɵeld(213, 0, null, null, 1, "a", [["href", "https://www.microsoft.com/en-us/sql-server/default.aspx"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Microsoft SQL"])), (_l()(), i1.ɵted(-1, null, [". "])), (_l()(), i1.ɵeld(216, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(217, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(218, 0, null, null, 3, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(219, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(220, 0, null, null, 1, "div", [["class", "bold"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["AT&T Weather Operations Site"])), (_l()(), i1.ɵeld(222, 0, null, null, 14, "div", [["class", "division-subgroup-content"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(223, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Continued work on an internal AT&T weather information site. The site combined feeds from a variety of sources which are used to provide forecast and current weather information for internal AT&T employees. Sources included, but not limited to, Satellite, Radar, Accu-weather Enterprise Services, and internal Microsoft SQL database feeds. The website employed the "])), (_l()(), i1.ɵeld(225, 0, null, null, 1, "a", [["href", "https://angularjs.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["AngularJS"])), (_l()(), i1.ɵted(-1, null, [" framework, "])), (_l()(), i1.ɵeld(228, 0, null, null, 1, "a", [["href", "https://www.asp.net/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["ASP .NET"])), (_l()(), i1.ɵted(-1, null, [" backend, "])), (_l()(), i1.ɵeld(231, 0, null, null, 1, "a", [["href", "https://www.visualstudio.com/vs/community/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Visual Studio"])), (_l()(), i1.ɵted(-1, null, [", and "])), (_l()(), i1.ɵeld(234, 0, null, null, 1, "a", [["href", "https://www.microsoft.com/en-us/sql-server/default.aspx"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Microsoft SQL"])), (_l()(), i1.ɵted(-1, null, [". "])), (_l()(), i1.ɵeld(237, 0, null, null, 1, "div", [["fxFlex", "0 0 20px"]], null, null, null, null, null)), i1.ɵdid(238, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(239, 0, null, null, 32, "div", [["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(240, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(241, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(242, 0, null, null, 2, "div", [["class", "division-title"], ["fxFlex", "0 0 auto"]], null, null, null, null, null)), i1.ɵdid(243, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵted(-1, null, [" Additional Experience, Leadership, and Volunteer Activities "])), (_l()(), i1.ɵeld(245, 0, null, null, 26, "div", [["class", "division-group"], ["fxFlex", "0 0 auto"], ["fxLayout", "column"]], null, null, null, null, null)), i1.ɵdid(246, 737280, null, 0, i2.LayoutDirective, [i3.MediaMonitor, i1.ElementRef, i3.StyleUtils], { layout: [0, "layout"] }, null), i1.ɵdid(247, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(248, 0, null, null, 5, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(249, 0, null, null, 1, "a", [["href", "https://www.hselpaso.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["El Paso Humane Society "])), (_l()(), i1.ɵted(-1, null, [" Animal Handler"])), (_l()(), i1.ɵeld(252, 0, null, null, 1, "span", [["class", "sub"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" \u2014 2+ years"])), (_l()(), i1.ɵeld(254, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(255, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(256, 0, null, null, 3, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(257, 0, null, null, 1, "a", [["href", "https://elpasoansfightinghunger.org/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["El Pasoans Fighting Hunger Food Bank"])), (_l()(), i1.ɵted(-1, null, [" Volunteer "])), (_l()(), i1.ɵeld(260, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(261, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(262, 0, null, null, 3, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵeld(263, 0, null, null, 1, "a", [["href", "https://www.faa.gov/licenses_certificates/airmen_certification/student_replacement/"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Faa Stuent Pilot"])), (_l()(), i1.ɵted(-1, null, [" - Private Pilot "])), (_l()(), i1.ɵeld(266, 0, null, null, 1, "div", [["fxFlex", "0 0 5px"]], null, null, null, null, null)), i1.ɵdid(267, 737280, null, 0, i2.FlexDirective, [i3.MediaMonitor, i1.ElementRef, [3, i2.LayoutDirective], i3.StyleUtils, [2, i3.ADD_FLEX_STYLES]], { flex: [0, "flex"] }, null), (_l()(), i1.ɵeld(268, 0, null, null, 3, "div", [["class", "division-subgroup-title"], ["fxFLex", "0 0 auto"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" El Paso Aspire Mentoring Academy program"])), (_l()(), i1.ɵeld(270, 0, null, null, 1, "span", [["class", "sub"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, [" \u2014 Mult-year volunteer and presentor"]))], function (_ck, _v) { var currVal_0 = "row"; _ck(_v, 1, 0, currVal_0); var currVal_1 = "center center"; _ck(_v, 2, 0, currVal_1); var currVal_2 = "column"; var currVal_3 = "row"; _ck(_v, 4, 0, currVal_2, currVal_3); var currVal_4 = "column"; _ck(_v, 6, 0, currVal_4); var currVal_5 = "0 0 auto"; var currVal_6 = "0 0 220px"; _ck(_v, 7, 0, currVal_5, currVal_6); var currVal_7 = "start center"; _ck(_v, 9, 0, currVal_7); var currVal_8 = "0 0 auto"; _ck(_v, 10, 0, currVal_8); var currVal_9 = "0 0 5px"; _ck(_v, 13, 0, currVal_9); var currVal_10 = "row wrap"; _ck(_v, 15, 0, currVal_10); var currVal_11 = "start center"; _ck(_v, 16, 0, currVal_11); var currVal_12 = "0 0 auto"; _ck(_v, 17, 0, currVal_12); var currVal_13 = "0 0 20px"; _ck(_v, 25, 0, currVal_13); var currVal_14 = "row"; _ck(_v, 27, 0, currVal_14); var currVal_15 = "start center"; _ck(_v, 28, 0, currVal_15); var currVal_16 = "0 0 auto"; _ck(_v, 29, 0, currVal_16); var currVal_17 = "row"; _ck(_v, 33, 0, currVal_17); var currVal_18 = "start center"; _ck(_v, 34, 0, currVal_18); var currVal_19 = "0 0 auto"; _ck(_v, 35, 0, currVal_19); var currVal_20 = "0 0 10px"; _ck(_v, 39, 0, currVal_20); var currVal_21 = "0 0 auto"; _ck(_v, 41, 0, currVal_21); var currVal_22 = "0 0 10px"; _ck(_v, 44, 0, currVal_22); var currVal_23 = "row"; _ck(_v, 46, 0, currVal_23); var currVal_24 = "start center"; _ck(_v, 47, 0, currVal_24); var currVal_25 = "0 0 auto"; _ck(_v, 48, 0, currVal_25); var currVal_26 = "column"; _ck(_v, 52, 0, currVal_26); var currVal_27 = "0 0 auto"; var currVal_28 = "1 1 100%"; _ck(_v, 53, 0, currVal_27, currVal_28); var currVal_29 = "0 0 20px"; _ck(_v, 55, 0, currVal_29); var currVal_30 = "column"; _ck(_v, 57, 0, currVal_30); var currVal_31 = "0 0 auto"; _ck(_v, 58, 0, currVal_31); var currVal_32 = "0 0 auto"; _ck(_v, 60, 0, currVal_32); var currVal_33 = "column"; _ck(_v, 63, 0, currVal_33); var currVal_34 = "0 0 auto"; _ck(_v, 64, 0, currVal_34); var currVal_35 = "0 0 auto"; _ck(_v, 71, 0, currVal_35); var currVal_36 = "0 0 auto"; _ck(_v, 85, 0, currVal_36); var currVal_37 = "0 0 auto"; _ck(_v, 91, 0, currVal_37); var currVal_38 = "0 0 20px"; _ck(_v, 108, 0, currVal_38); var currVal_39 = "column"; _ck(_v, 110, 0, currVal_39); var currVal_40 = "0 0 auto"; _ck(_v, 111, 0, currVal_40); var currVal_41 = "0 0 auto"; _ck(_v, 113, 0, currVal_41); var currVal_42 = "column"; _ck(_v, 116, 0, currVal_42); var currVal_43 = "0 0 auto"; _ck(_v, 117, 0, currVal_43); var currVal_44 = "0 0 auto"; _ck(_v, 125, 0, currVal_44); var currVal_45 = "0 0 auto"; _ck(_v, 128, 0, currVal_45); var currVal_46 = "0 0 10px"; _ck(_v, 131, 0, currVal_46); var currVal_47 = "0 0 auto"; _ck(_v, 133, 0, currVal_47); var currVal_48 = "row"; _ck(_v, 137, 0, currVal_48); var currVal_49 = "0 0 auto"; _ck(_v, 138, 0, currVal_49); var currVal_50 = "0 0 15px"; _ck(_v, 140, 0, currVal_50); var currVal_51 = "row"; _ck(_v, 156, 0, currVal_51); var currVal_52 = "0 0 auto"; _ck(_v, 157, 0, currVal_52); var currVal_53 = "0 0 15px"; _ck(_v, 159, 0, currVal_53); var currVal_54 = "column"; _ck(_v, 175, 0, currVal_54); var currVal_55 = "0 0 auto"; _ck(_v, 176, 0, currVal_55); var currVal_56 = "0 0 auto"; _ck(_v, 184, 0, currVal_56); var currVal_57 = "0 0 auto"; _ck(_v, 190, 0, currVal_57); var currVal_58 = "0 0 5px"; _ck(_v, 193, 0, currVal_58); var currVal_59 = "0 0 auto"; _ck(_v, 195, 0, currVal_59); var currVal_60 = "0 0 auto"; _ck(_v, 199, 0, currVal_60); var currVal_61 = "0 0 5px"; _ck(_v, 217, 0, currVal_61); var currVal_62 = "0 0 auto"; _ck(_v, 219, 0, currVal_62); var currVal_63 = "0 0 auto"; _ck(_v, 223, 0, currVal_63); var currVal_64 = "0 0 20px"; _ck(_v, 238, 0, currVal_64); var currVal_65 = "column"; _ck(_v, 240, 0, currVal_65); var currVal_66 = "0 0 auto"; _ck(_v, 241, 0, currVal_66); var currVal_67 = "0 0 auto"; _ck(_v, 243, 0, currVal_67); var currVal_68 = "column"; _ck(_v, 246, 0, currVal_68); var currVal_69 = "0 0 auto"; _ck(_v, 247, 0, currVal_69); var currVal_70 = "0 0 5px"; _ck(_v, 255, 0, currVal_70); var currVal_71 = "0 0 5px"; _ck(_v, 261, 0, currVal_71); var currVal_72 = "0 0 5px"; _ck(_v, 267, 0, currVal_72); }, null); }
exports.View_HomeComponent_0 = View_HomeComponent_0;
function View_HomeComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-home", [], null, null, null, View_HomeComponent_0, RenderType_HomeComponent)), i1.ɵdid(1, 114688, null, 0, i4.HomeComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_HomeComponent_Host_0 = View_HomeComponent_Host_0;
var HomeComponentNgFactory = i1.ɵccf("app-home", i4.HomeComponent, View_HomeComponent_Host_0, {}, {}, []);
exports.HomeComponentNgFactory = HomeComponentNgFactory;


/***/ }),

/***/ "./src/app/home/home.component.ts":
/*!****************************************!*\
  !*** ./src/app/home/home.component.ts ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var HomeComponent = /** @class */ (function () {
    function HomeComponent() {
    }
    HomeComponent.prototype.ngOnInit = function () {
        this.message = 'Hello';
    };
    return HomeComponent;
}());
exports.HomeComponent = HomeComponent;


/***/ }),

/***/ "./src/app/home/home.css.shim.ngstyle.js":
/*!***********************************************!*\
  !*** ./src/app/home/home.css.shim.ngstyle.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".container[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n    height: 100%;\r\n}\r\n\r\n.content[_ngcontent-%COMP%] {\r\n    height: 100%;\r\n    width: 100%;\r\n    max-width: 1060px;\r\n\r\n    \r\n}\r\n\r\n.container-margin[_ngcontent-%COMP%] {\r\n    margin: 10px 10px;\r\n}\r\n\r\n.img[_ngcontent-%COMP%] {\r\n    padding: 15px;\r\n    max-width: 200px;\r\n}\r\n\r\n.name-text[_ngcontent-%COMP%]   span[_ngcontent-%COMP%] {\r\n    font-size: 48px;\r\n    font-family: 'RobotoBold', sans-serif;\r\n\r\n    margin-left: 5px;\r\n    margin-right: 5px;\r\n\r\n    color: rgb(33, 150, 243);\r\n}\r\n\r\na[_ngcontent-%COMP%] {\r\n    text-decoration: none;\r\n    background-color: aliceblue;\r\n    color: rgb(158, 158, 158);\r\n    padding: 0px 5px;\r\n    cursor: pointer;\r\n}\r\n\r\na[_ngcontent-%COMP%]:hover {\r\n    color: rgb(33, 150, 243);\r\n}\r\n\r\n.division-title[_ngcontent-%COMP%] { \r\n    font-size: 24px;\r\n    font-family: 'RobotoBold', sans-serif;\r\n    color: rgb(33, 150, 243);\r\n}\r\n\r\n.division-group[_ngcontent-%COMP%] {\r\n    margin: 10px;\r\n}\r\n\r\n.division-subgroup-title[_ngcontent-%COMP%] {\r\n   font-size: 18px; \r\n   color: rgb(100, 100, 100);\r\n   font-family: 'RobotoBold', sans-serif;\r\n}\r\n\r\n.division-subgroup-title[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\r\n    font-size: 18px; \r\n    color: rgb(100, 100, 100);\r\n}\r\n\r\n.division-subgroup-title[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\r\n    color: rgb(33, 150, 243);\r\n}\r\n\r\n.division-subgroup-title[_ngcontent-%COMP%]   .sub[_ngcontent-%COMP%] {\r\n    font-family: 'Roboto', sans-serif;\r\n    font-size: 16px;\r\n}\r\n\r\n.division-subgroup-content[_ngcontent-%COMP%] {\r\n    font-size: 16px;\r\n    margin-top: 2px;\r\n    color: rgb(158, 158, 158);\r\n}\r\n\r\n.division-subgroup-content[_ngcontent-%COMP%]   .bold[_ngcontent-%COMP%] {\r\n    font-family: 'RobotoBold', sans-serif;\r\n}\r\n\r\n.division-subgroup-content[_ngcontent-%COMP%]   .publication[_ngcontent-%COMP%] {\r\n    font-size: 12px;\r\n    font-style: italic;\r\n}\r\n\r\n.card[_ngcontent-%COMP%] {\r\n    transition: all 0.5s ease-out;\r\n}\r\n\r\n.card[_ngcontent-%COMP%]:hover {\r\n    border-radius: 2px;\r\n    box-shadow: 0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23);\r\n    padding: 1rem;\r\n}\r\n\r\n.u-flexFix[_ngcontent-%COMP%] {\r\n    max-height: 100% !important;\r\n}"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/lazy/lazy.module.ngfactory.js":
/*!***********************************************!*\
  !*** ./src/app/lazy/lazy.module.ngfactory.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./lazy.module */ "./src/app/lazy/lazy.module.ts");
var i2 = __webpack_require__(/*! @angular/router */ "@angular/router");
var LazyModuleNgFactory = i0.ɵcmf(i1.LazyModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [LazyComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(1073742336, i2.RouterModule, i2.RouterModule, [[2, i2.ɵangular_packages_router_router_a], [2, i2.Router]]), i0.ɵmpd(1073742336, i1.LazyModule, i1.LazyModule, []), i0.ɵmpd(1024, i2.ROUTES, function () { return [[{ path: "", component: i1.LazyComponent, pathMatch: "full" }]]; }, [])]); });
exports.LazyModuleNgFactory = LazyModuleNgFactory;
var styles_LazyComponent = [];
var RenderType_LazyComponent = i0.ɵcrt({ encapsulation: 2, styles: styles_LazyComponent, data: {} });
exports.RenderType_LazyComponent = RenderType_LazyComponent;
function View_LazyComponent_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "h3", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["i'm lazy"]))], null, null); }
exports.View_LazyComponent_0 = View_LazyComponent_0;
function View_LazyComponent_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-lazy-view", [], null, null, null, View_LazyComponent_0, RenderType_LazyComponent)), i0.ɵdid(1, 49152, null, 0, i1.LazyComponent, [], null, null)], null, null); }
exports.View_LazyComponent_Host_0 = View_LazyComponent_Host_0;
var LazyComponentNgFactory = i0.ɵccf("app-lazy-view", i1.LazyComponent, View_LazyComponent_Host_0, {}, {}, []);
exports.LazyComponentNgFactory = LazyComponentNgFactory;


/***/ }),

/***/ "./src/app/lazy/lazy.module.ts":
/*!*************************************!*\
  !*** ./src/app/lazy/lazy.module.ts ***!
  \*************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var LazyComponent = /** @class */ (function () {
    function LazyComponent() {
    }
    return LazyComponent;
}());
exports.LazyComponent = LazyComponent;
var LazyModule = /** @class */ (function () {
    function LazyModule() {
    }
    return LazyModule;
}());
exports.LazyModule = LazyModule;


/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
var __lazy_0__ = __webpack_require__(/*! ./app/lazy/lazy.module.ngfactory.js */ "./src/app/lazy/lazy.module.ngfactory.js");
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = { "./lazy/lazy.module#LazyModule": __lazy_0__.LazyModuleNgFactory };


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! D:\git\universal-starter\src\main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/cdk/bidi":
/*!************************************!*\
  !*** external "@angular/cdk/bidi" ***!
  \************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/cdk/bidi");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/flex-layout":
/*!***************************************!*\
  !*** external "@angular/flex-layout" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/flex-layout");

/***/ }),

/***/ "@angular/flex-layout/core":
/*!********************************************!*\
  !*** external "@angular/flex-layout/core" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/flex-layout/core");

/***/ }),

/***/ "@angular/flex-layout/extended":
/*!************************************************!*\
  !*** external "@angular/flex-layout/extended" ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/flex-layout/extended");

/***/ }),

/***/ "@angular/flex-layout/flex":
/*!********************************************!*\
  !*** external "@angular/flex-layout/flex" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/flex-layout/flex");

/***/ }),

/***/ "@angular/flex-layout/server":
/*!**********************************************!*\
  !*** external "@angular/flex-layout/server" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/flex-layout/server");

/***/ }),

/***/ "@angular/http":
/*!********************************!*\
  !*** external "@angular/http" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/http");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@angular/router":
/*!**********************************!*\
  !*** external "@angular/router" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/router");

/***/ }),

/***/ "@angular/service-worker":
/*!******************************************!*\
  !*** external "@angular/service-worker" ***!
  \******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/service-worker");

/***/ }),

/***/ "@nguniversal/common":
/*!**************************************!*\
  !*** external "@nguniversal/common" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/common");

/***/ }),

/***/ "@nguniversal/module-map-ngfactory-loader":
/*!***********************************************************!*\
  !*** external "@nguniversal/module-map-ngfactory-loader" ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/module-map-ngfactory-loader");

/***/ })

/******/ })));